name: Deploy to Proxmon VM from Webhook

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: Log level
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug
  repository_dispatch:
    types:
      - deploy

jobs:
  ssh_command:
    name: Run SSH command
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run command on remote server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          port: ${{ secrets.SSH_PORT }}
          service_token_id: ${{ secrets.SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.SERVICE_TOKEN_SECRET }}
          commands: |
            cd /home/tems/apps/tems-platform
            docker compose up -d --build
